name: Uploading to Google Drive

on:
    push:
        branches: [main]

permissions:
    contents: read  # Permissão para ler o conteúdo do repositório
    issues: write    # Permissão para escrever em issues
    pull-requests: write  # Permissão para escrever em pull requests

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: |
                    /assets/
                    pack.mcmeta