name: Deploy Resource Pack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Archive
        uses: thedoctor0/zip-release@master
        with:
          filename: 'Santy112Pack.zip'
          exclusions: '*.git* .github/* README.md .vscode/*'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./ 
          publish_branch: gh-pages
          keep_files: true 
          enable_jekyll: true 