name: Update Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Archive
        uses: thedoctor0/zip-release@master
        with:
          filename: 'Santy112Pack.zip'
          exclusions: '*.git* .github/* README.md .vscode/*'

      - name: Update Release
        uses: pyTooling/Actions/releaser@r0
        with:
          tag: latest # Uma tag fixa chamada "latest"
          rm_targs: Santy112Pack.zip # Remove o zip antigo
          files: Santy112Pack.zip
          token: ${{ secrets.GITHUB_TOKEN }}